# Generated by Django 5.0.4 on 2024-05-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='CholesterolContent',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='FiberContent',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='SaturatedFatContent',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='SodiumContent',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='SugarContent',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Calories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='CarbohydrateContent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='FatContent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ProteinContent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
