# Generated by Django 5.0.4 on 2024-06-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_recipe_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ImageURLs',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Images',
            field=models.ImageField(upload_to='recipe_images/'),
        ),
    ]
