# Generated by Django 5.0.4 on 2024-06-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_recipe_authorid_alter_recipe_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ImageURLs',
            field=models.TextField(),
        ),
    ]
