# Generated by Django 5.0.4 on 2024-06-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_recipe_imageurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ImageURL',
            field=models.TextField(default=''),
        ),
    ]
