# Generated by Django 5.0.4 on 2024-06-04 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recipe_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ImageURL',
        ),
    ]
