# Generated by Django 5.0.4 on 2024-06-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_profile_allergylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='allergies',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allergylist',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.TextField(max_length=100),
        ),
    ]
