# Generated by Django 5.0.4 on 2024-06-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_profile_allergies_alter_profile_allergylist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.TextField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='recipes',
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allergylist',
            field=models.TextField(default=list),
        ),
    ]
